# Generated by Django 5.2.1 on 2025-05-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='market',
            new_name='markets',
        ),
    ]
